<h1 align="center">Урок 4. Непрерывные случайные величины. Функция распределения и плотность распределения вероятностей. Равномерное и нормальное распределение. Центральная предельная теорема</h1>

In [1]:
from scipy import stats

1. Случайная непрерывная величина A имеет равномерное распределение на промежутке (200, 800]. Найдите ее среднее значение и дисперсию.

$$ M(X) = \frac{a+b}{2} = \frac{200+800}{2} = 500 $$

$$ D(X) = \frac{(b-a)^2}{12} = \frac{(800-200)^2}{12} = 30000$$

2. О случайной непрерывной равномерно распределенной величине B известно, что ее дисперсия равна 0.2.
Можно ли найти правую границу величины B и ее среднее значение зная, что левая граница равна 0.5?
Если да, найдите ее.

$ Выразим\ b\ из\ формулы\ D(X) = \frac{(b-a)^2}{12}: $

$$ (b-a)^2 = 12D(X) $$

$$ b^2 - 2ab + a^2 = 12D(X) $$

$$ b^2 - 2ab + a^2 - 12D(X) = 0 $$

$$ b_{1, 2} = \frac{2a \pm \sqrt{(-2a)^2-4*(a^2 - 12D(X))}}{2} $$

$ Подставим\ исходные\ значения\ величин: $

$$ b_{1, 2} = \frac{2*0.5 \pm \sqrt{4*0,25-4*(0.5^2 - 12*0.2)}}{2} = \frac{1 \pm \sqrt{9.6}}{2} = 
\begin{cases}
  2.05 \\ -1.05
\end{cases}$$

$ b_2 = -1.05\ не\ удовлетворяет\ условию\ задачи,\ поэтому\ правой\ границей\ является\ b_1 = 2.05$

$$  M(X) = \frac{a+b}{2} = \frac{0.5+2.05}{2} = 1.275 $$

3. Непрерывная случайная величина X распределена нормально и задана плотностью распределения
$ f(x) = (\frac{1}{4 * \sqrt{2\pi}}) * e^{\frac{-(x+2)^2}{32}}. $
Найдите:<br>
а) M(X)<br>
б) D(X)<br>
в) std(X) (среднее квадратичное отклонение)

$ f(x) = (\frac{1}{\sigma * \sqrt{2\pi}}) * e^{\frac{-(x-M(x))^2}{2\sigma^2}}, => Отсюда\ M(X) = -2, D(X) = 16, std(X) = 4$

4. Рост взрослого населения города X имеет нормальное распределение.
Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см.
Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:<br>
а) больше 182 см<br>
б) больше 190 см<br>
в) от 166 см до 190 см<br>
г) от 166 см до 182 см<br>
д) от 158 см до 190 см<br>
е) не выше 150 см или не ниже 190 см<br>
ё) не выше 150 см или не ниже 198 см<br>
ж) ниже 166 см.

In [2]:
avg = 174
sd = 8

$ a)\ P(X>182) = 1 - P(X \le 182) = 1 - P\left(Z \le \frac{X-M(X)}{S(X)}\right) = 1 - P\left(Z \le \frac{182-174}{8}\right) = 1 - P(Z \le 1) = 1 - 0.8413 = 0.1587 $

In [3]:
x = 182
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост больше {x} см "
       f"равна {1 - stats.norm.cdf((x-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост больше 182 см равна 0.15865525393145707


$ б)\ P(X>190) = 1 - P(X \le 190) = 1 - P\left(Z \le \frac{190-174}{8}\right) = 1 - P(Z \le 2) = 1 - 0.9772 = 0.0228 $

In [4]:
x = 190
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост больше {x} см "
       f"равна {1 - stats.norm.cdf((x-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост больше 190 см равна 0.02275013194817921


$ в)\ P(166<X<190) = P\left(Z \le \frac{190-174}{8}\right) - P\left(Z \le \frac{166-174}{8}\right) = P(Z \le 2) - P(Z \le -1) = 0.9772 - 0.1587 = 0.8185 $

In [5]:
x_1, x_2 = 166, 190
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост от {x_1} см до {x_2} см "
       f"равна {stats.norm.cdf((x_2-avg)/sd) - stats.norm.cdf((x_1-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост от 166 см до 190 см равна 0.8185946141203637


$ г)\ P(166<X<182) = P\left(Z \le \frac{182-174}{8}\right) - P\left(Z \le \frac{166-174}{8}\right) = P(Z \le 1) - P(Z \le -1) = 0.8413 - 0.1587 = 0.6826 $

In [6]:
x_1, x_2 = 166, 182
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост от {x_1} см до {x_2} см "
       f"равна {stats.norm.cdf((x_2-avg)/sd) - stats.norm.cdf((x_1-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост от 166 см до 182 см равна 0.6826894921370859


$ д)\ P(158<X<190) = P\left(Z \le \frac{190-174}{8}\right) - P\left(Z \le \frac{158-174}{8}\right) = P(Z \le 2) - P(Z \le -2) = 0.9772 - 0.0228 = 0.9544 $

In [7]:
x_1, x_2 = 158, 190
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост от {x_1} см до {x_2} см "
       f"равна {stats.norm.cdf((x_2-avg)/sd) - stats.norm.cdf((x_1-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост от 158 см до 190 см равна 0.9544997361036416


$ е)\ P(X<150, X>190) = P\left(Z \le \frac{150-174}{8}\right) + 1 - P\left(Z \le \frac{190-174}{8}\right) = P(Z \le -3) + 1 -P(Z \le 2) = 0.0014 + 1 - 0.9772 = 0.0242 $

In [8]:
x_1, x_2 = 150, 190
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост не выше {x_1} см или не ниже {x_2} см "
       f"равна {stats.norm.cdf((x_1-avg)/sd) + 1- stats.norm.cdf((x_2-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост не выше 150 см или не ниже 190 см равна 0.0241000299798092


$ ё)\ P(X<150, X>198) = P\left(Z \le \frac{150-174}{8}\right) + 1 - P\left(Z \le \frac{198-174}{8}\right) = P(Z \le -3) + 1 -P(Z \le 3) = 0.0014 + 1 - 0.9987 = 0.0027 $

In [9]:
x_1, x_2 = 150, 198
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост не выше {x_1} см или не ниже {x_2} см "
       f"равна {stats.norm.cdf((x_1-avg)/sd) + 1- stats.norm.cdf((x_2-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост не выше 150 см или не ниже 198 см равна 0.002699796063260096


$ ж)\ P(X<166) =  P\left(Z \le \frac{166-174}{8}\right) = 0.1587 $

In [10]:
x = 166
print(f"Вероятность того, что случайным образом выбранный взрослый человек имеет рост ниже {x} см "
       f"равна {stats.norm.cdf((x-avg)/sd)}")

Вероятность того, что случайным образом выбранный взрослый человек имеет рост ниже 166 см равна 0.15865525393145707


5. На сколько сигм (средних квадратичных отклонений) отклоняется рост человека, равный 190 см, от
математического ожидания роста в популяции, в которой M(X) = 178 см и D(X) = 25 кв.см?

$$ Z = \frac{X-M(X)}{S(X)} = \frac{X-M(X)}{\sqrt{D(X)}} = \frac{190-178}{\sqrt{25}} = 2.4$$